name: gauge_chart
description: This Flutter package provides a customizable circular, gauge-style pie chart that can be displayed as a full circle or half circle
version: 1.0.1
homepage: https://github.com/gheomg/gauge_chart.git
platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
